// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6LTo1hVsD8_CJtDX1J7PgUQuMJp2zpGE',
    appId: '1:768590484115:web:6aa4c178be732648473366',
    messagingSenderId: '768590484115',
    projectId: 'flutter-chat-app-7e631',
    authDomain: 'flutter-chat-app-7e631.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7e631.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3iufDkGhUdKxruEDTIHL6ei_W2s592U',
    appId: '1:768590484115:android:cebfb69878458087473366',
    messagingSenderId: '768590484115',
    projectId: 'flutter-chat-app-7e631',
    storageBucket: 'flutter-chat-app-7e631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtIl8Igjezwaw8AEIQ7aLlgwy1DFUvkCM',
    appId: '1:768590484115:ios:2b6c8c22320037ab473366',
    messagingSenderId: '768590484115',
    projectId: 'flutter-chat-app-7e631',
    storageBucket: 'flutter-chat-app-7e631.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtIl8Igjezwaw8AEIQ7aLlgwy1DFUvkCM',
    appId: '1:768590484115:ios:2b6c8c22320037ab473366',
    messagingSenderId: '768590484115',
    projectId: 'flutter-chat-app-7e631',
    storageBucket: 'flutter-chat-app-7e631.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6LTo1hVsD8_CJtDX1J7PgUQuMJp2zpGE',
    appId: '1:768590484115:web:cc8965f499fbb0d0473366',
    messagingSenderId: '768590484115',
    projectId: 'flutter-chat-app-7e631',
    authDomain: 'flutter-chat-app-7e631.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7e631.firebasestorage.app',
  );

}